/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Forget the device cookie in this browser (the device stays registered until revoked).
     */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/pair": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Redeem Pairing Code
     * @description Register this browser with the role attached to a pairing code (QR flow).
     */
    post: operations["redeem_pairing_code_api_v1_auth_pair_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Redeem Setup Code
     * @description Register this browser as an admin device using the setup code printed at startup.
     */
    post: operations["redeem_setup_code_api_v1_auth_setup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/collections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Collections */
    get: operations["list_collections_api_v1_collections_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Devices */
    get: operations["list_devices_api_v1_devices_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices/pairing-codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Pairing Code */
    post: operations["create_pairing_code_api_v1_devices_pairing_codes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/devices/{device_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Device */
    delete: operations["revoke_device_api_v1_devices__device_id__delete"];
    options?: never;
    head?: never;
    /** Update Device */
    patch: operations["update_device_api_v1_devices__device_id__patch"];
    trace?: never;
  };
  "/api/v1/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Events
     * @description Server-sent events: `photo.ingested`, `photo.ingest_failed`, `job.progress`, `job.failed`.
     */
    get: operations["events_api_v1_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/inbox/dismiss": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dismiss From Inbox */
    post: operations["dismiss_from_inbox_api_v1_inbox_dismiss_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/inbox/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore To Inbox */
    post: operations["restore_to_inbox_api_v1_inbox_restore_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/localsend/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Devices */
    get: operations["list_devices_api_v1_localsend_devices_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/localsend/devices/{device_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Forget Device */
    delete: operations["forget_device_api_v1_localsend_devices__device_id__delete"];
    options?: never;
    head?: never;
    /** Update Device */
    patch: operations["update_device_api_v1_localsend_devices__device_id__patch"];
    trace?: never;
  };
  "/api/v1/localsend/requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pending Requests */
    get: operations["pending_requests_api_v1_localsend_requests_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/localsend/requests/{request_id}/decision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Decide */
    post: operations["decide_api_v1_localsend_requests__request_id__decision_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/localsend/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Status */
    get: operations["status_api_v1_localsend_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/photos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Photos */
    get: operations["list_photos_api_v1_photos_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/photos/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Library Stats */
    get: operations["library_stats_api_v1_photos_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/photos/{photo_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Photo */
    get: operations["get_photo_api_v1_photos__photo_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Photo */
    patch: operations["update_photo_api_v1_photos__photo_id__patch"];
    trace?: never;
  };
  "/api/v1/photos/{photo_id}/original": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Photo Original */
    get: operations["photo_original_api_v1_photos__photo_id__original_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/photos/{photo_id}/proxy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Photo Proxy */
    get: operations["photo_proxy_api_v1_photos__photo_id__proxy_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/photos/{photo_id}/thumb/{size}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Photo Thumb */
    get: operations["photo_thumb_api_v1_photos__photo_id__thumb__size__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** System Info */
    get: operations["system_info_api_v1_system_info_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_v1_system_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Tags */
    get: operations["list_tags_api_v1_tags_get"];
    put?: never;
    /**
     * Create Tag
     * @description Create a tag, or return the existing one with the same name (case-insensitive).
     */
    post: operations["create_tag_api_v1_tags_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Upload
     * @description Open a resumable upload session, or resume the existing one for the same file.
     */
    post: operations["create_upload_api_v1_uploads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/uploads/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Check Hashes
     * @description Tell which files (by SHA-256) are already known, so clients can skip them.
     */
    post: operations["check_hashes_api_v1_uploads_check_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/uploads/{upload_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Upload */
    get: operations["get_upload_api_v1_uploads__upload_id__get"];
    put?: never;
    post?: never;
    /** Cancel Upload */
    delete: operations["cancel_upload_api_v1_uploads__upload_id__delete"];
    options?: never;
    /** Head Upload */
    head: operations["head_upload_api_v1_uploads__upload_id__head"];
    /**
     * Append Chunk
     * @description Append a chunk at `Upload-Offset`. Completing the file verifies it and starts ingestion.
     */
    patch: operations["append_chunk_api_v1_uploads__upload_id__patch"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Capabilities */
    Capabilities: {
      /** Avif */
      avif: boolean;
      /** Color Management */
      color_management: boolean;
      /** Libvips Version */
      libvips_version: string;
      /** Ultra Hdr */
      ultra_hdr: boolean;
    };
    /** CodeRedeemIn */
    CodeRedeemIn: {
      /** Code */
      code: string;
      /**
       * Device Name
       * @default
       */
      device_name: string;
    };
    /** CollectionOut */
    CollectionOut: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "manual" | "smart";
      /** Name */
      name: string;
      /** Parent Id */
      parent_id: string | null;
      /** Position */
      position: number;
    };
    /** CountOut */
    CountOut: {
      /** Count */
      count: number;
    };
    /** DeviceOut */
    DeviceOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Id */
      id: string;
      /** Last Seen At */
      last_seen_at: string | null;
      /** Name */
      name: string;
      /**
       * Role
       * @enum {string}
       */
      role: "admin" | "uploader";
      /** User Agent */
      user_agent: string;
    };
    /** DeviceUpdateIn */
    DeviceUpdateIn: {
      /** Name */
      name?: string | null;
      /** Role */
      role?: ("admin" | "uploader") | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HashCheckIn */
    HashCheckIn: {
      /** Sha256 */
      sha256: string[];
    };
    /** HashCheckOut */
    HashCheckOut: {
      /** Results */
      results: components["schemas"]["HashStatusOut"][];
    };
    /** HashStatusOut */
    HashStatusOut: {
      /** Offset */
      offset?: number | null;
      /** Photo Id */
      photo_id?: string | null;
      /** Sha256 */
      sha256: string;
      /**
       * Status
       * @enum {string}
       */
      status: "new" | "exists" | "in_progress";
      /** Upload Id */
      upload_id?: string | null;
    };
    /** LibraryStats */
    LibraryStats: {
      /** Inbox */
      inbox: number;
      /** Photos */
      photos: number;
    };
    /** LocalSendDecisionIn */
    LocalSendDecisionIn: {
      /** Approve */
      approve: boolean;
    };
    /** LocalSendDeviceOut */
    LocalSendDeviceOut: {
      /** Alias */
      alias: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Device Model */
      device_model: string | null;
      /** Device Type */
      device_type: string | null;
      /** Id */
      id: string;
      /** Last Ip */
      last_ip: string | null;
      /** Last Seen At */
      last_seen_at: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "pending" | "approved" | "blocked";
    };
    /** LocalSendDeviceUpdateIn */
    LocalSendDeviceUpdateIn: {
      /**
       * Status
       * @enum {string}
       */
      status: "pending" | "approved" | "blocked";
    };
    /** LocalSendRequestOut */
    LocalSendRequestOut: {
      /** Alias */
      alias: string;
      /** Created At */
      created_at: string;
      /** Device Id */
      device_id: string;
      /** Device Model */
      device_model: string | null;
      /** File Count */
      file_count: number;
      /** Id */
      id: string;
      /** Ip */
      ip: string;
      /** Total Bytes */
      total_bytes: number;
    };
    /** LocalSendStatusOut */
    LocalSendStatusOut: {
      /** Alias */
      alias: string;
      /** Discovery */
      discovery: boolean;
      /** Enabled */
      enabled: boolean;
      /** Error */
      error: string | null;
      /** Fingerprint */
      fingerprint: string | null;
      /** Port */
      port: number;
      /** Running */
      running: boolean;
    };
    /** Me */
    Me: {
      /** Authenticated */
      authenticated: boolean;
      /** Device Id */
      device_id: string | null;
      /** Device Name */
      device_name: string | null;
      /** Role */
      role: ("admin" | "uploader") | null;
      /** Setup Required */
      setup_required: boolean;
      /**
       * Via
       * @enum {string}
       */
      via: "device" | "localhost" | "anonymous";
    };
    /** PairingCodeIn */
    PairingCodeIn: {
      /**
       * Role
       * @default uploader
       * @enum {string}
       */
      role: "admin" | "uploader";
    };
    /** PairingCodeOut */
    PairingCodeOut: {
      /** Code */
      code: string;
      /** Expires In Seconds */
      expires_in_seconds: number;
      /**
       * Role
       * @enum {string}
       */
      role: "admin" | "uploader";
      /** Url */
      url: string;
    };
    /** PhotoIdsIn */
    PhotoIdsIn: {
      /** Photo Ids */
      photo_ids: string[];
    };
    /** PhotoOut */
    PhotoOut: {
      /** Bit Depth */
      bit_depth: number;
      /** Camera Make */
      camera_make: string | null;
      /** Camera Model */
      camera_model: string | null;
      /** File Size */
      file_size: number;
      /** Gps Lat */
      gps_lat: number | null;
      /** Gps Lon */
      gps_lon: number | null;
      /** Has Gain Map */
      has_gain_map: boolean;
      /** Height */
      height: number;
      /** Icc Description */
      icc_description: string | null;
      /** Id */
      id: string;
      /**
       * Imported At
       * Format: date-time
       */
      imported_at: string;
      /**
       * Inbox State
       * @enum {string}
       */
      inbox_state: "inbox" | "processed" | "dismissed";
      /** Is Wide Gamut */
      is_wide_gamut: boolean;
      /** Lens */
      lens: string | null;
      /** Mime */
      mime: string;
      /** Original Filename */
      original_filename: string;
      /** Place Admin1 */
      place_admin1: string | null;
      /** Place Country */
      place_country: string | null;
      /** Place Name */
      place_name: string | null;
      /** Quality Warnings */
      quality_warnings: string[];
      /** Sha256 */
      sha256: string;
      /** Tags */
      tags?: components["schemas"]["TagOut"][];
      /** Taken At */
      taken_at: string | null;
      /** Width */
      width: number;
    };
    /** PhotoPageOut */
    PhotoPageOut: {
      /** Items */
      items: components["schemas"]["PhotoOut"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** PhotoUpdateIn */
    PhotoUpdateIn: {
      /** Inbox State */
      inbox_state?: ("inbox" | "processed" | "dismissed") | null;
      /** Tag Ids */
      tag_ids?: string[] | null;
    };
    /** SystemInfo */
    SystemInfo: {
      capabilities: components["schemas"]["Capabilities"];
      /** Max Upload Bytes */
      max_upload_bytes: number;
      /** Name */
      name: string;
      /** Public Url */
      public_url: string;
      /** Upload Chunk Bytes */
      upload_chunk_bytes: number;
      /** Version */
      version: string;
    };
    /** TagCreateIn */
    TagCreateIn: {
      /** Name */
      name: string;
    };
    /** TagOut */
    TagOut: {
      /** Color */
      color: string | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
    };
    /** TagWithCount */
    TagWithCount: {
      /** Color */
      color: string | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Photo Count */
      photo_count: number;
    };
    /** UploadCreateIn */
    UploadCreateIn: {
      /** Filename */
      filename: string;
      meta?: components["schemas"]["UploadMetaIn"] | null;
      /**
       * Mime
       * @default
       */
      mime: string;
      /** Sha256 */
      sha256: string;
      /** Size */
      size: number;
    };
    /** UploadMetaIn */
    UploadMetaIn: {
      /** Collection Ids */
      collection_ids?: string[];
      /**
       * Favorite
       * @default false
       */
      favorite: boolean;
      /** Tag Ids */
      tag_ids?: string[];
    };
    /** UploadOut */
    UploadOut: {
      /** Chunk Bytes */
      chunk_bytes: number;
      /** Error */
      error?: string | null;
      /**
       * Offset
       * @default 0
       */
      offset: number;
      /** Photo Id */
      photo_id?: string | null;
      /** Size */
      size: number;
      /**
       * Status
       * @enum {string}
       */
      status: "open" | "processing" | "failed" | "exists";
      /** Upload Id */
      upload_id?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  redeem_pairing_code_api_v1_auth_pair_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeRedeemIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  redeem_setup_code_api_v1_auth_setup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeRedeemIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_collections_api_v1_collections_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CollectionOut"][];
        };
      };
    };
  };
  list_devices_api_v1_devices_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceOut"][];
        };
      };
    };
  };
  create_pairing_code_api_v1_devices_pairing_codes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PairingCodeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PairingCodeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_device_api_v1_devices__device_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_device_api_v1_devices__device_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeviceUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  events_api_v1_events_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  dismiss_from_inbox_api_v1_inbox_dismiss_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PhotoIdsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CountOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  restore_to_inbox_api_v1_inbox_restore_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PhotoIdsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CountOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_devices_api_v1_localsend_devices_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocalSendDeviceOut"][];
        };
      };
    };
  };
  forget_device_api_v1_localsend_devices__device_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_device_api_v1_localsend_devices__device_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocalSendDeviceUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocalSendDeviceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pending_requests_api_v1_localsend_requests_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocalSendRequestOut"][];
        };
      };
    };
  };
  decide_api_v1_localsend_requests__request_id__decision_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocalSendDecisionIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  status_api_v1_localsend_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocalSendStatusOut"];
        };
      };
    };
  };
  list_photos_api_v1_photos_get: {
    parameters: {
      query?: {
        inbox_state?: ("inbox" | "processed" | "dismissed") | null;
        q?: string | null;
        tag_id?: string | null;
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PhotoPageOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  library_stats_api_v1_photos_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryStats"];
        };
      };
    };
  };
  get_photo_api_v1_photos__photo_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PhotoOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_photo_api_v1_photos__photo_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PhotoUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PhotoOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  photo_original_api_v1_photos__photo_id__original_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  photo_proxy_api_v1_photos__photo_id__proxy_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  photo_thumb_api_v1_photos__photo_id__thumb__size__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
        size: "256" | "768";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  system_info_api_v1_system_info_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemInfo"];
        };
      };
    };
  };
  me_api_v1_system_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  list_tags_api_v1_tags_get: {
    parameters: {
      query?: {
        q?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TagWithCount"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_tag_api_v1_tags_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagCreateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TagOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_upload_api_v1_uploads_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadCreateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  check_hashes_api_v1_uploads_check_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HashCheckIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HashCheckOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_upload_api_v1_uploads__upload_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        upload_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_upload_api_v1_uploads__upload_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        upload_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  head_upload_api_v1_uploads__upload_id__head: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        upload_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  append_chunk_api_v1_uploads__upload_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        upload_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/offset+octet-stream": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
