"""initial schema

Revision ID: bee796d06711
Revises:
Create Date: 2026-09-16 18:04:45.578422
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bee796d06711"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artworks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("document_version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("worst_tier", sa.String(length=16), nullable=True),
        sa.Column("min_scale", sa.Float(), nullable=True),
        sa.Column("max_scale", sa.Float(), nullable=True),
        sa.Column("photo_count", sa.Integer(), nullable=False),
        sa.Column("is_incomplete", sa.Boolean(), nullable=False),
        sa.Column("origin_style_id", sa.String(length=36), nullable=True),
        sa.Column("origin_style_revision", sa.Integer(), nullable=True),
        sa.Column("origin_layout_id", sa.String(length=36), nullable=True),
        sa.Column("origin_layout_revision", sa.Integer(), nullable=True),
        sa.Column("render_hash", sa.String(length=64), nullable=True),
        sa.Column("rendered_at", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.Column("deleted_at", sa.String(length=32), nullable=True),
        sa.Column("trash_batch_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artworks", schema=None) as batch_op:
        batch_op.create_index("ix_artworks_created", ["created_at", "id"], unique=False)

    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.String(length=32), nullable=True),
        sa.Column("revoked_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "frame_styles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("builtin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("lane", sa.String(length=16), nullable=False),
        sa.Column("coalesce_key", sa.String(length=128), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.String(length=32), nullable=True),
        sa.Column("finished_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_claim", ["lane", "state", "created_at"], unique=False)
        batch_op.create_index("ix_jobs_coalesce", ["coalesce_key", "state"], unique=False)

    op.create_table(
        "layouts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("slot_count", sa.Integer(), nullable=False),
        sa.Column("builtin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pairing_codes",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.String(length=32), nullable=False),
        sa.Column("used_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("code_hash"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "setup_codes",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.String(length=32), nullable=False),
        sa.Column("used_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("code_hash"),
    )
    op.create_table(
        "swatches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128, collation="NOCASE"), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_key", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("mime", sa.String(length=128), nullable=False),
        sa.Column("received_bytes", sa.Integer(), nullable=False),
        sa.Column("pending_meta", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("error", sa.String(length=128), nullable=True),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_upload_sessions_lookup", ["device_key", "sha256", "size", "state"], unique=False
        )

    op.create_table(
        "artwork_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artwork_id", sa.String(length=36), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("document_version", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["artwork_id"], ["artworks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artwork_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artwork_snapshots_artwork_id"), ["artwork_id"], unique=False
        )

    op.create_table(
        "artwork_tags",
        sa.Column("artwork_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["artwork_id"], ["artworks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("artwork_id", "tag_id"),
    )
    op.create_table(
        "collections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("date_start", sa.String(length=10), nullable=True),
        sa.Column("date_end", sa.String(length=10), nullable=True),
        sa.Column("cover_artwork_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("filter", sa.JSON(), nullable=True),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["cover_artwork_id"], ["artworks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_collections_parent_id"), ["parent_id"], unique=False)

    op.create_table(
        "photos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("ext", sa.String(length=8), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("exif_orientation", sa.Integer(), nullable=False),
        sa.Column("bit_depth", sa.Integer(), nullable=False),
        sa.Column("icc_description", sa.String(length=256), nullable=True),
        sa.Column("is_wide_gamut", sa.Boolean(), nullable=False),
        sa.Column("has_gain_map", sa.Boolean(), nullable=False),
        sa.Column("taken_at", sa.String(length=32), nullable=True),
        sa.Column("camera_make", sa.String(length=128), nullable=True),
        sa.Column("camera_model", sa.String(length=128), nullable=True),
        sa.Column("lens", sa.String(length=128), nullable=True),
        sa.Column("gps_lat", sa.Float(), nullable=True),
        sa.Column("gps_lon", sa.Float(), nullable=True),
        sa.Column("place_name", sa.String(length=256), nullable=True),
        sa.Column("place_admin1", sa.String(length=256), nullable=True),
        sa.Column("place_country", sa.String(length=128), nullable=True),
        sa.Column("uploaded_by_device_id", sa.String(length=36), nullable=True),
        sa.Column("imported_at", sa.String(length=32), nullable=False),
        sa.Column("inbox_state", sa.String(length=16), nullable=False),
        sa.Column("quality_warnings", sa.JSON(), nullable=False),
        sa.Column("deleted_at", sa.String(length=32), nullable=True),
        sa.Column("trash_batch_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["uploaded_by_device_id"], ["devices.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.create_index("ix_photos_imported", ["imported_at", "id"], unique=False)
        batch_op.create_index("ix_photos_inbox", ["inbox_state", "imported_at"], unique=False)
        batch_op.create_index("ix_photos_taken", ["taken_at"], unique=False)

    op.create_table(
        "artwork_photos",
        sa.Column("artwork_id", sa.String(length=36), nullable=False),
        sa.Column("slot_id", sa.String(length=64), nullable=False),
        sa.Column("photo_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["artwork_id"], ["artworks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["photo_id"], ["photos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("artwork_id", "slot_id"),
    )
    with op.batch_alter_table("artwork_photos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artwork_photos_photo_id"), ["photo_id"], unique=False)

    op.create_table(
        "collection_items",
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("artwork_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["artwork_id"], ["artworks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("collection_id", "artwork_id"),
    )
    with op.batch_alter_table("collection_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_collection_items_artwork_id"), ["artwork_id"], unique=False
        )

    op.create_table(
        "photo_pending_meta",
        sa.Column("photo_id", sa.String(length=36), nullable=False),
        sa.Column("collection_ids", sa.JSON(), nullable=False),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["photo_id"], ["photos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("photo_id"),
    )
    op.create_table(
        "photo_tags",
        sa.Column("photo_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["photo_id"], ["photos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("photo_id", "tag_id"),
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE VIRTUAL TABLE search_index USING fts5("
        "entity_type UNINDEXED, entity_id UNINDEXED, text, tokenize='unicode61 remove_diacritics 2')"
    )


def downgrade() -> None:
    op.execute("DROP TABLE search_index")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("photo_tags")
    op.drop_table("photo_pending_meta")
    with op.batch_alter_table("collection_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collection_items_artwork_id"))

    op.drop_table("collection_items")
    with op.batch_alter_table("artwork_photos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artwork_photos_photo_id"))

    op.drop_table("artwork_photos")
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.drop_index("ix_photos_taken")
        batch_op.drop_index("ix_photos_inbox")
        batch_op.drop_index("ix_photos_imported")

    op.drop_table("photos")
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collections_parent_id"))

    op.drop_table("collections")
    op.drop_table("artwork_tags")
    with op.batch_alter_table("artwork_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artwork_snapshots_artwork_id"))

    op.drop_table("artwork_snapshots")
    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_upload_sessions_lookup")

    op.drop_table("upload_sessions")
    op.drop_table("tags")
    op.drop_table("swatches")
    op.drop_table("setup_codes")
    op.drop_table("settings")
    op.drop_table("pairing_codes")
    op.drop_table("layouts")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_coalesce")
        batch_op.drop_index("ix_jobs_claim")

    op.drop_table("jobs")
    op.drop_table("frame_styles")
    op.drop_table("devices")
    with op.batch_alter_table("artworks", schema=None) as batch_op:
        batch_op.drop_index("ix_artworks_created")

    op.drop_table("artworks")
    # ### end Alembic commands ###
